name: build
on: [push]
jobs:
  build-macos-10-14-client:
    runs-on: macos-10.14
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - run: brew install swig
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade setuptools wheel delocate
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cd secrethub-xgo && go build -o ../secrethub/Client.dylib -buildmode=c-shared secrethub_wrapper.go
      - run: python setup.py bdist_wheel
      - run: delocate-listdeps --all dist/*.whl
      - run: export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$(pwd)/secrethub && delocate-wheel -v dist/*.whl
      - uses: actions/upload-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-macos-10-14
          path: dist
  build-macos-10-15-client:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - run: brew install swig
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade setuptools wheel delocate
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cd secrethub-xgo && go build -o ../secrethub/Client.dylib -buildmode=c-shared secrethub_wrapper.go
      - run: python setup.py bdist_wheel
      - run: delocate-listdeps --all dist/*.whl
      - run: export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$(pwd)/secrethub && delocate-wheel -v dist/*.whl
      - uses: actions/upload-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-macos-10-15
          path: dist
  build-linux-client:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cd secrethub-xgo && go build -o ../secrethub/Client.so -buildmode=c-shared secrethub_wrapper.go
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade setuptools wheel
      - run: python setup.py bdist_wheel
      - run: docker run -v $(pwd):/secrethub quay.io/pypa/manylinux2014_x86_64 bash -c "cd /secrethub && auditwheel show dist/*.whl"
      - run: docker run -v $(pwd):/secrethub quay.io/pypa/manylinux2014_x86_64 bash -c "cd /secrethub && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:\$(pwd):/usr/local/lib && auditwheel repair dist/*.whl"
      - uses: actions/upload-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-linux
          path: wheelhouse
  build-win32-dll:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt install -y gcc-mingw-w64
      - run: cd secrethub-xgo && GOOS=windows GOARCH=386 CGO_ENABLED=1 CC=i686-w64-mingw32-gcc go build -o ../Client.dll -buildmode=c-shared secrethub_wrapper.go
      - uses: actions/upload-artifact@v2
        with:
          name: client-dll-win32
          path: ./Client.dll
  build-win32-client:
    needs: [build-win32-dll]
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x86'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - run: cd secrethub && lib /def:Client.def /out:Client.lib /machine:x86
      - uses: actions/download-artifact@v2
        with:
          name: client-dll-win32
          path: ./secrethub
      - run: cd secrethub && Rename-Item -Path "Client32.h" -NewName "Client.h" # Workaround for having edited header files
      - run: cd secrethub && Rename-Item -Path "Client.dll" -NewName "CLIENT.dll"
      - run: python -m pip install --upgrade setuptools wheel
      - run: choco install swig
      - run: python setup.py bdist_wheel --plat-name=win32
      - run: mkdir wheelhouse
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x86'
      - run: python -m pip install pefile machomachomangler
      - run: python utilities/wheel-repair.py ./dist/*.whl -d ./secrethub
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-win32
          path: wheelhouse
  build-win64-dll:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt install -y gcc-mingw-w64
      - run: cd secrethub-xgo && GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -o ../Client.dll -buildmode=c-shared secrethub_wrapper.go
      - uses: actions/upload-artifact@v2
        with:
          name: client-dll-win64
          path: ./Client.dll
  build-win64-client:
    needs: [build-win64-dll]
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - run: cd secrethub && lib /def:Client.def /out:Client.lib /machine:x64
      - uses: actions/download-artifact@v2
        with:
          name: client-dll-win64
          path: ./secrethub
      - run: cd secrethub && Rename-Item -Path "Client64.h" -NewName "Client.h" # Workaround for having edited header files
      - run: cd secrethub && Rename-Item -Path "Client.dll" -NewName "CLIENT.dll"
      - run: python -m pip install --upgrade setuptools wheel
      - run: choco install swig
      - run: python setup.py bdist_wheel --plat-name=win-amd64
      - run: mkdir wheelhouse
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python -m pip install pefile machomachomangler
      - run: python utilities/wheel-repair.py ./dist/*.whl -d ./secrethub
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-win64
          path: wheelhouse
  test-linux-client:
    needs: [build-linux-client]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/download-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-linux
          path: .
      - run: python -m pip install *.whl
      - run: python -m unittest test/test.py
  test-win64-client:
    needs: [build-win64-client]
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/download-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-win64
          path: .
      - run: python -m pip install *.whl
        shell: bash
      - run: python -m unittest test/test.py
  test-win32-client:
    needs: [build-win32-client]
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x86'
      - uses: actions/download-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-win32
          path: .
      - run: python -m pip install *.whl
        shell: bash
      - run: python -m unittest test/test.py
  test-macos-10-15:
    needs: [build-macos-10-15-client]
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-macos-10-15
          path: .
      - run: python -m pip install *.whl
      - run: python -m unittest test/test.py
  test-macos-10-14:
    needs: [build-macos-10-14-client]
    runs-on: macos-10.14
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v2
        with:
          name: secrethub-python-${{ matrix.python-version }}-macos-10-14
          path: .
      - run: python -m pip install *.whl
      - run: python -m unittest test/test.py
