name: build
on: [push]
jobs:
  build-win32-dll:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt install -y gcc-mingw-w64
      - run: cd secrethub-xgo && GOOS=windows GOARCH=386 CGO_ENABLED=1 CC=i686-w64-mingw32-gcc go build -o ../Client.dll -buildmode=c-shared secrethub_wrapper.go
      - uses: actions/upload-artifact@v2 
        with: 
          name: client-dll-win32
          path: ./Client.dll
  build-win32-client:
    needs: [build-win32-dll]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: ilammy/msvc-dev-cmd@v1
        with: 
          arch: x86
      - run: lib /def:Client.def /out:Client.lib /machine:x86
      - uses: actions/download-artifact@v2 
        with: 
          name: client-dll-win32
          path: ./build/
      - run: Rename-Item -Path "Client32.h" -NewName "Client.h" # Workaround for having edited header files
      - run: cl.exe /c /O2 secrethub_wrap.c /I C:\hostedtoolcache\windows\Python\3.8.6\x64\include
      - run: cl.exe /LD secrethub_wrap.obj Client.lib /link C:\hostedtoolcache\windows\Python\3.8.6\x86\libs\python3.lib
      - run: Rename-Item -Path "secrethub_wrap.dll" -NewName "_secrethub.pyd"
      - uses: actions/upload-artifact@v2
        with:
          name: secrethub-python-win32
          path: |
            _secrethub.pyd
            Client.dll
  build-win64-dll:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt install -y gcc-mingw-w64
      - run: cd secrethub-xgo && GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -o ../Client.dll -buildmode=c-shared secrethub_wrapper.go
      - uses: actions/upload-artifact@v2
        with:
          name: client-dll-win64
          path: ./Client.dll
  build-win64-client:
    needs: [build-win64-dll]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - run: lib /def:Client.def /out:Client.lib /machine:x64
      - uses: actions/download-artifact@v2
        with:
          name: client-dll-win64
          path: ./build/
      - run: Rename-Item -Path "Client64.h" -NewName "Client.h" # Workaround for having edited header files
      - run: cl.exe /c /O2 secrethub_wrap.c /I C:\hostedtoolcache\windows\Python\3.8.6\x64\include
      - run: cl.exe /LD secrethub_wrap.obj Client.lib /link C:\hostedtoolcache\windows\Python\3.8.6\x64\libs\python3.lib
      - run: Rename-Item -Path "secrethub_wrap.dll" -NewName "_secrethub.pyd"
      - uses: actions/upload-artifact@v2
        with:
          name: secrethub-python-win64
          path: |
            _secrethub.pyd
            Client.dll
  test-win64-client:
    needs: [build-win64-client]
    runs-on: windows-2019
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/download-artifact@v2
        with:
          name: client-dll-win64
          path: .
      - uses: actions/download-artifact@v2
        with:
          name: secrethub-python-win64
          path: .
      - run: dir
      - run: python -c "import secrethub; client = secrethub.Client(); print(client.read_string('test/test/test'))"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -c "import secrethub; client = secrethub.Client(); print(client.read_string('test/test/test'))"
