name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker run winamd64/python:3.9 -- cd "C:\Python" && tree
