name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cd "C:\hostedtoolcache\windows\Python\3.7.9\" && tree
