name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: python -c "import os, sys; print(os.path.dirname(sys.executable))"
      - run: cd "C:\Program Files\Python" && tree
